version: '3.9'

x-app: &app
  env_file:
    - .env

services:

  api:
    build: .
    container_name: movies-api
    <<: *app
    expose:
      - 8000
    networks:
      - etl_network
      - jaeger_net

  redis:
    image: redis:7.0.10
    container_name: movies-redis
    <<: *app
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 30s
    expose:
      - 6379
    restart: unless-stopped
    networks:
      - etl_network

  nginx:
    image: nginx:latest
    container_name: movies-nginx
    ports:
      - 82:82
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - etl_network

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
    networks:
      - jaeger_net


volumes:
  redis_data:

networks:
  jaeger_net:
  etl_network:
    external: true
